# Generated by Django 4.0.2 on 2022-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_tag_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='viewer.Tag'),
        ),
    ]
