# Generated by Django 4.0.2 on 2022-05-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
