# Generated by Django 4.0.2 on 2022-06-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_movietag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('born', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
                ('movies', models.ManyToManyField(blank=True, null=True, to='viewer.Movie')),
            ],
        ),
    ]
